# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # desc "Description of what the lane does"
  # lane :custom_lane do
  #   # add actions here: https://docs.fastlane.tools/actions
  # end

  desc "Create ipa"
  lane :build do
    cocoapods(
      clean_install: true,
      podfile: "./Podfile"
    )
    match(app_identifier: "com.mercadolibre.*", type: "development", readonly: true)
    gym
    sh "bash ../scripts/saucelabs.sh"
  end
  lane :build_local do
    xcodebuild(
      {
        clean: true,
        build: true,
        derivedDataPath: "build",
        workspace: "./ExampleSwift.xcworkspace",
        output_name: "ExampleSwift.app",
        scheme: "ExampleSwift",
        sdk: "iphonesimulator",
        xcargs: "ONLY_ACTIVE_ARCH=NO"
      }
    )
  end
end
